// This file was generated by counterfeiter
package uniform_fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics/client"
	"github.com/momchil-atanasov/go-whiskey/graphics/uniform"
)

type FakeTextureUniformValue struct {
	BindStub        func(uniformClient client.UniformClient, channel int, location client.UniformLocation)
	bindMutex       sync.RWMutex
	bindArgsForCall []struct {
		uniformClient client.UniformClient
		channel       int
		location      client.UniformLocation
	}
}

func (fake *FakeTextureUniformValue) Bind(uniformClient client.UniformClient, channel int, location client.UniformLocation) {
	fake.bindMutex.Lock()
	fake.bindArgsForCall = append(fake.bindArgsForCall, struct {
		uniformClient client.UniformClient
		channel       int
		location      client.UniformLocation
	}{uniformClient, channel, location})
	fake.bindMutex.Unlock()
	if fake.BindStub != nil {
		fake.BindStub(uniformClient, channel, location)
	}
}

func (fake *FakeTextureUniformValue) BindCallCount() int {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	return len(fake.bindArgsForCall)
}

func (fake *FakeTextureUniformValue) BindArgsForCall(i int) (client.UniformClient, int, client.UniformLocation) {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	return fake.bindArgsForCall[i].uniformClient, fake.bindArgsForCall[i].channel, fake.bindArgsForCall[i].location
}

var _ uniform.TextureUniformValue = new(FakeTextureUniformValue)
