// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics"
)

type FakeFacade struct {
	CreateBufferStub        func() graphics.ResourceID
	createBufferMutex       sync.RWMutex
	createBufferArgsForCall []struct{}
	createBufferReturns struct {
		result1 graphics.ResourceID
	}
	BindIndexBufferStub        func(bufferId graphics.ResourceID)
	bindIndexBufferMutex       sync.RWMutex
	bindIndexBufferArgsForCall []struct {
		bufferId graphics.ResourceID
	}
	CreateIndexBufferDataStub        func(data []byte, usage graphics.BufferUsage)
	createIndexBufferDataMutex       sync.RWMutex
	createIndexBufferDataArgsForCall []struct {
		data  []byte
		usage graphics.BufferUsage
	}
	DeleteBufferStub        func(bufferId graphics.ResourceID)
	deleteBufferMutex       sync.RWMutex
	deleteBufferArgsForCall []struct {
		bufferId graphics.ResourceID
	}
	CreateVertexShaderStub        func() graphics.ResourceID
	createVertexShaderMutex       sync.RWMutex
	createVertexShaderArgsForCall []struct{}
	createVertexShaderReturns struct {
		result1 graphics.ResourceID
	}
	CreateFragmentShaderStub        func() graphics.ResourceID
	createFragmentShaderMutex       sync.RWMutex
	createFragmentShaderArgsForCall []struct{}
	createFragmentShaderReturns struct {
		result1 graphics.ResourceID
	}
	SetShaderSourceCodeStub        func(shaderId graphics.ResourceID, sourceCode string)
	setShaderSourceCodeMutex       sync.RWMutex
	setShaderSourceCodeArgsForCall []struct {
		shaderId   graphics.ResourceID
		sourceCode string
	}
	CompileShaderStub        func(shaderId graphics.ResourceID)
	compileShaderMutex       sync.RWMutex
	compileShaderArgsForCall []struct {
		shaderId graphics.ResourceID
	}
	DeleteShaderStub        func(shaderId graphics.ResourceID)
	deleteShaderMutex       sync.RWMutex
	deleteShaderArgsForCall []struct {
		shaderId graphics.ResourceID
	}
}

func (fake *FakeFacade) CreateBuffer() graphics.ResourceID {
	fake.createBufferMutex.Lock()
	fake.createBufferArgsForCall = append(fake.createBufferArgsForCall, struct{}{})
	fake.createBufferMutex.Unlock()
	if fake.CreateBufferStub != nil {
		return fake.CreateBufferStub()
	} else {
		return fake.createBufferReturns.result1
	}
}

func (fake *FakeFacade) CreateBufferCallCount() int {
	fake.createBufferMutex.RLock()
	defer fake.createBufferMutex.RUnlock()
	return len(fake.createBufferArgsForCall)
}

func (fake *FakeFacade) CreateBufferReturns(result1 graphics.ResourceID) {
	fake.CreateBufferStub = nil
	fake.createBufferReturns = struct {
		result1 graphics.ResourceID
	}{result1}
}

func (fake *FakeFacade) BindIndexBuffer(bufferId graphics.ResourceID) {
	fake.bindIndexBufferMutex.Lock()
	fake.bindIndexBufferArgsForCall = append(fake.bindIndexBufferArgsForCall, struct {
		bufferId graphics.ResourceID
	}{bufferId})
	fake.bindIndexBufferMutex.Unlock()
	if fake.BindIndexBufferStub != nil {
		fake.BindIndexBufferStub(bufferId)
	}
}

func (fake *FakeFacade) BindIndexBufferCallCount() int {
	fake.bindIndexBufferMutex.RLock()
	defer fake.bindIndexBufferMutex.RUnlock()
	return len(fake.bindIndexBufferArgsForCall)
}

func (fake *FakeFacade) BindIndexBufferArgsForCall(i int) graphics.ResourceID {
	fake.bindIndexBufferMutex.RLock()
	defer fake.bindIndexBufferMutex.RUnlock()
	return fake.bindIndexBufferArgsForCall[i].bufferId
}

func (fake *FakeFacade) CreateIndexBufferData(data []byte, usage graphics.BufferUsage) {
	fake.createIndexBufferDataMutex.Lock()
	fake.createIndexBufferDataArgsForCall = append(fake.createIndexBufferDataArgsForCall, struct {
		data  []byte
		usage graphics.BufferUsage
	}{data, usage})
	fake.createIndexBufferDataMutex.Unlock()
	if fake.CreateIndexBufferDataStub != nil {
		fake.CreateIndexBufferDataStub(data, usage)
	}
}

func (fake *FakeFacade) CreateIndexBufferDataCallCount() int {
	fake.createIndexBufferDataMutex.RLock()
	defer fake.createIndexBufferDataMutex.RUnlock()
	return len(fake.createIndexBufferDataArgsForCall)
}

func (fake *FakeFacade) CreateIndexBufferDataArgsForCall(i int) ([]byte, graphics.BufferUsage) {
	fake.createIndexBufferDataMutex.RLock()
	defer fake.createIndexBufferDataMutex.RUnlock()
	return fake.createIndexBufferDataArgsForCall[i].data, fake.createIndexBufferDataArgsForCall[i].usage
}

func (fake *FakeFacade) DeleteBuffer(bufferId graphics.ResourceID) {
	fake.deleteBufferMutex.Lock()
	fake.deleteBufferArgsForCall = append(fake.deleteBufferArgsForCall, struct {
		bufferId graphics.ResourceID
	}{bufferId})
	fake.deleteBufferMutex.Unlock()
	if fake.DeleteBufferStub != nil {
		fake.DeleteBufferStub(bufferId)
	}
}

func (fake *FakeFacade) DeleteBufferCallCount() int {
	fake.deleteBufferMutex.RLock()
	defer fake.deleteBufferMutex.RUnlock()
	return len(fake.deleteBufferArgsForCall)
}

func (fake *FakeFacade) DeleteBufferArgsForCall(i int) graphics.ResourceID {
	fake.deleteBufferMutex.RLock()
	defer fake.deleteBufferMutex.RUnlock()
	return fake.deleteBufferArgsForCall[i].bufferId
}

func (fake *FakeFacade) CreateVertexShader() graphics.ResourceID {
	fake.createVertexShaderMutex.Lock()
	fake.createVertexShaderArgsForCall = append(fake.createVertexShaderArgsForCall, struct{}{})
	fake.createVertexShaderMutex.Unlock()
	if fake.CreateVertexShaderStub != nil {
		return fake.CreateVertexShaderStub()
	} else {
		return fake.createVertexShaderReturns.result1
	}
}

func (fake *FakeFacade) CreateVertexShaderCallCount() int {
	fake.createVertexShaderMutex.RLock()
	defer fake.createVertexShaderMutex.RUnlock()
	return len(fake.createVertexShaderArgsForCall)
}

func (fake *FakeFacade) CreateVertexShaderReturns(result1 graphics.ResourceID) {
	fake.CreateVertexShaderStub = nil
	fake.createVertexShaderReturns = struct {
		result1 graphics.ResourceID
	}{result1}
}

func (fake *FakeFacade) CreateFragmentShader() graphics.ResourceID {
	fake.createFragmentShaderMutex.Lock()
	fake.createFragmentShaderArgsForCall = append(fake.createFragmentShaderArgsForCall, struct{}{})
	fake.createFragmentShaderMutex.Unlock()
	if fake.CreateFragmentShaderStub != nil {
		return fake.CreateFragmentShaderStub()
	} else {
		return fake.createFragmentShaderReturns.result1
	}
}

func (fake *FakeFacade) CreateFragmentShaderCallCount() int {
	fake.createFragmentShaderMutex.RLock()
	defer fake.createFragmentShaderMutex.RUnlock()
	return len(fake.createFragmentShaderArgsForCall)
}

func (fake *FakeFacade) CreateFragmentShaderReturns(result1 graphics.ResourceID) {
	fake.CreateFragmentShaderStub = nil
	fake.createFragmentShaderReturns = struct {
		result1 graphics.ResourceID
	}{result1}
}

func (fake *FakeFacade) SetShaderSourceCode(shaderId graphics.ResourceID, sourceCode string) {
	fake.setShaderSourceCodeMutex.Lock()
	fake.setShaderSourceCodeArgsForCall = append(fake.setShaderSourceCodeArgsForCall, struct {
		shaderId   graphics.ResourceID
		sourceCode string
	}{shaderId, sourceCode})
	fake.setShaderSourceCodeMutex.Unlock()
	if fake.SetShaderSourceCodeStub != nil {
		fake.SetShaderSourceCodeStub(shaderId, sourceCode)
	}
}

func (fake *FakeFacade) SetShaderSourceCodeCallCount() int {
	fake.setShaderSourceCodeMutex.RLock()
	defer fake.setShaderSourceCodeMutex.RUnlock()
	return len(fake.setShaderSourceCodeArgsForCall)
}

func (fake *FakeFacade) SetShaderSourceCodeArgsForCall(i int) (graphics.ResourceID, string) {
	fake.setShaderSourceCodeMutex.RLock()
	defer fake.setShaderSourceCodeMutex.RUnlock()
	return fake.setShaderSourceCodeArgsForCall[i].shaderId, fake.setShaderSourceCodeArgsForCall[i].sourceCode
}

func (fake *FakeFacade) CompileShader(shaderId graphics.ResourceID) {
	fake.compileShaderMutex.Lock()
	fake.compileShaderArgsForCall = append(fake.compileShaderArgsForCall, struct {
		shaderId graphics.ResourceID
	}{shaderId})
	fake.compileShaderMutex.Unlock()
	if fake.CompileShaderStub != nil {
		fake.CompileShaderStub(shaderId)
	}
}

func (fake *FakeFacade) CompileShaderCallCount() int {
	fake.compileShaderMutex.RLock()
	defer fake.compileShaderMutex.RUnlock()
	return len(fake.compileShaderArgsForCall)
}

func (fake *FakeFacade) CompileShaderArgsForCall(i int) graphics.ResourceID {
	fake.compileShaderMutex.RLock()
	defer fake.compileShaderMutex.RUnlock()
	return fake.compileShaderArgsForCall[i].shaderId
}

func (fake *FakeFacade) DeleteShader(shaderId graphics.ResourceID) {
	fake.deleteShaderMutex.Lock()
	fake.deleteShaderArgsForCall = append(fake.deleteShaderArgsForCall, struct {
		shaderId graphics.ResourceID
	}{shaderId})
	fake.deleteShaderMutex.Unlock()
	if fake.DeleteShaderStub != nil {
		fake.DeleteShaderStub(shaderId)
	}
}

func (fake *FakeFacade) DeleteShaderCallCount() int {
	fake.deleteShaderMutex.RLock()
	defer fake.deleteShaderMutex.RUnlock()
	return len(fake.deleteShaderArgsForCall)
}

func (fake *FakeFacade) DeleteShaderArgsForCall(i int) graphics.ResourceID {
	fake.deleteShaderMutex.RLock()
	defer fake.deleteShaderMutex.RUnlock()
	return fake.deleteShaderArgsForCall[i].shaderId
}

var _ graphics.Facade = new(FakeFacade)
