// Generated by 'github.com/momchil-atanasov/gostub'

package graphics_stubs

import (
	sync "sync"

	alias1 "github.com/momchil-atanasov/go-whiskey/graphics"
)

type FlatTextureStub struct {
	StubGUID            int
	SetTexelStub        func(arg1 int, arg2 int, arg3 alias1.RGBAColor)
	setTexelMutex       sync.RWMutex
	setTexelArgsForCall []struct {
		arg1 int
		arg2 int
		arg3 alias1.RGBAColor
	}
	TexelStub        func(arg1 int, arg2 int) (result1 alias1.RGBAColor)
	texelMutex       sync.RWMutex
	texelArgsForCall []struct {
		arg1 int
		arg2 int
	}
	texelReturns struct {
		result1 alias1.RGBAColor
	}
}

var _ alias1.FlatTexture = new(FlatTextureStub)

func (stub *FlatTextureStub) SetTexel(arg1 int, arg2 int, arg3 alias1.RGBAColor) {
	stub.setTexelMutex.Lock()
	defer stub.setTexelMutex.Unlock()
	stub.setTexelArgsForCall = append(stub.setTexelArgsForCall, struct {
		arg1 int
		arg2 int
		arg3 alias1.RGBAColor
	}{arg1, arg2, arg3})
	if stub.SetTexelStub != nil {
		stub.SetTexelStub(arg1, arg2, arg3)
	}
}
func (stub *FlatTextureStub) SetTexelCallCount() int {
	stub.setTexelMutex.RLock()
	defer stub.setTexelMutex.RUnlock()
	return len(stub.setTexelArgsForCall)
}
func (stub *FlatTextureStub) SetTexelArgsForCall(index int) (int, int, alias1.RGBAColor) {
	stub.setTexelMutex.RLock()
	defer stub.setTexelMutex.RUnlock()
	return stub.setTexelArgsForCall[index].arg1, stub.setTexelArgsForCall[index].arg2, stub.setTexelArgsForCall[index].arg3
}
func (stub *FlatTextureStub) Texel(arg1 int, arg2 int) alias1.RGBAColor {
	stub.texelMutex.Lock()
	defer stub.texelMutex.Unlock()
	stub.texelArgsForCall = append(stub.texelArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	if stub.TexelStub != nil {
		return stub.TexelStub(arg1, arg2)
	} else {
		return stub.texelReturns.result1
	}
}
func (stub *FlatTextureStub) TexelCallCount() int {
	stub.texelMutex.RLock()
	defer stub.texelMutex.RUnlock()
	return len(stub.texelArgsForCall)
}
func (stub *FlatTextureStub) TexelArgsForCall(index int) (int, int) {
	stub.texelMutex.RLock()
	defer stub.texelMutex.RUnlock()
	return stub.texelArgsForCall[index].arg1, stub.texelArgsForCall[index].arg2
}
func (stub *FlatTextureStub) TexelReturns(result1 alias1.RGBAColor) {
	stub.texelMutex.Lock()
	defer stub.texelMutex.Unlock()
	stub.texelReturns = struct {
		result1 alias1.RGBAColor
	}{result1}
}
