// Generated by 'github.com/mokiat/gostub'

package graphics_stubs

import (
	alias1 "github.com/mokiat/go-whiskey/graphics"
)

type MaterialMechanismStub struct {
	StubGUID int
}

var _ alias1.MaterialMechanism = new(MaterialMechanismStub)
