// Generated by 'github.com/momchil-atanasov/gostub'

package graphics_stubs

import (
	alias1 "github.com/momchil-atanasov/go-whiskey/graphics"
)

type MechanismStub struct {
	StubGUID int
}

var _ alias1.Mechanism = new(MechanismStub)
