// Generated by 'github.com/mokiat/gostub'

package graphics_stubs

import (
	alias1 "github.com/mokiat/go-whiskey/graphics"
)

type UniformStub struct {
	StubGUID int
}

var _ alias1.Uniform = new(UniformStub)
