// This file was generated by counterfeiter
package buffer_fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics/buffer"
	"github.com/momchil-atanasov/go-whiskey/graphics/client"
)

type FakeVertexBuffer struct {
	DataStub        func() buffer.VertexBufferData
	dataMutex       sync.RWMutex
	dataArgsForCall []struct{}
	dataReturns struct {
		result1 buffer.VertexBufferData
	}
	UsageStub        func() client.BufferUsage
	usageMutex       sync.RWMutex
	usageArgsForCall []struct{}
	usageReturns struct {
		result1 client.BufferUsage
	}
	IdStub        func() client.BufferId
	idMutex       sync.RWMutex
	idArgsForCall []struct{}
	idReturns struct {
		result1 client.BufferId
	}
	CreatedStub        func() bool
	createdMutex       sync.RWMutex
	createdArgsForCall []struct{}
	createdReturns struct {
		result1 bool
	}
	CreateStub        func(client.BufferClient) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 client.BufferClient
	}
	createReturns struct {
		result1 error
	}
	DeleteStub        func(client.BufferClient) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 client.BufferClient
	}
	deleteReturns struct {
		result1 error
	}
}

func (fake *FakeVertexBuffer) Data() buffer.VertexBufferData {
	fake.dataMutex.Lock()
	fake.dataArgsForCall = append(fake.dataArgsForCall, struct{}{})
	fake.dataMutex.Unlock()
	if fake.DataStub != nil {
		return fake.DataStub()
	} else {
		return fake.dataReturns.result1
	}
}

func (fake *FakeVertexBuffer) DataCallCount() int {
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	return len(fake.dataArgsForCall)
}

func (fake *FakeVertexBuffer) DataReturns(result1 buffer.VertexBufferData) {
	fake.DataStub = nil
	fake.dataReturns = struct {
		result1 buffer.VertexBufferData
	}{result1}
}

func (fake *FakeVertexBuffer) Usage() client.BufferUsage {
	fake.usageMutex.Lock()
	fake.usageArgsForCall = append(fake.usageArgsForCall, struct{}{})
	fake.usageMutex.Unlock()
	if fake.UsageStub != nil {
		return fake.UsageStub()
	} else {
		return fake.usageReturns.result1
	}
}

func (fake *FakeVertexBuffer) UsageCallCount() int {
	fake.usageMutex.RLock()
	defer fake.usageMutex.RUnlock()
	return len(fake.usageArgsForCall)
}

func (fake *FakeVertexBuffer) UsageReturns(result1 client.BufferUsage) {
	fake.UsageStub = nil
	fake.usageReturns = struct {
		result1 client.BufferUsage
	}{result1}
}

func (fake *FakeVertexBuffer) Id() client.BufferId {
	fake.idMutex.Lock()
	fake.idArgsForCall = append(fake.idArgsForCall, struct{}{})
	fake.idMutex.Unlock()
	if fake.IdStub != nil {
		return fake.IdStub()
	} else {
		return fake.idReturns.result1
	}
}

func (fake *FakeVertexBuffer) IdCallCount() int {
	fake.idMutex.RLock()
	defer fake.idMutex.RUnlock()
	return len(fake.idArgsForCall)
}

func (fake *FakeVertexBuffer) IdReturns(result1 client.BufferId) {
	fake.IdStub = nil
	fake.idReturns = struct {
		result1 client.BufferId
	}{result1}
}

func (fake *FakeVertexBuffer) Created() bool {
	fake.createdMutex.Lock()
	fake.createdArgsForCall = append(fake.createdArgsForCall, struct{}{})
	fake.createdMutex.Unlock()
	if fake.CreatedStub != nil {
		return fake.CreatedStub()
	} else {
		return fake.createdReturns.result1
	}
}

func (fake *FakeVertexBuffer) CreatedCallCount() int {
	fake.createdMutex.RLock()
	defer fake.createdMutex.RUnlock()
	return len(fake.createdArgsForCall)
}

func (fake *FakeVertexBuffer) CreatedReturns(result1 bool) {
	fake.CreatedStub = nil
	fake.createdReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeVertexBuffer) Create(arg1 client.BufferClient) error {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 client.BufferClient
	}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	} else {
		return fake.createReturns.result1
	}
}

func (fake *FakeVertexBuffer) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeVertexBuffer) CreateArgsForCall(i int) client.BufferClient {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *FakeVertexBuffer) CreateReturns(result1 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVertexBuffer) Delete(arg1 client.BufferClient) error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 client.BufferClient
	}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeVertexBuffer) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeVertexBuffer) DeleteArgsForCall(i int) client.BufferClient {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].arg1
}

func (fake *FakeVertexBuffer) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

var _ buffer.VertexBuffer = new(FakeVertexBuffer)
