// This file was generated by counterfeiter
package render_fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics/render"
)

type FakeRenderer struct {
	RenderStub        func(render.Queue)
	renderMutex       sync.RWMutex
	renderArgsForCall []struct {
		arg1 render.Queue
	}
}

func (fake *FakeRenderer) Render(arg1 render.Queue) {
	fake.renderMutex.Lock()
	fake.renderArgsForCall = append(fake.renderArgsForCall, struct {
		arg1 render.Queue
	}{arg1})
	fake.renderMutex.Unlock()
	if fake.RenderStub != nil {
		fake.RenderStub(arg1)
	}
}

func (fake *FakeRenderer) RenderCallCount() int {
	fake.renderMutex.RLock()
	defer fake.renderMutex.RUnlock()
	return len(fake.renderArgsForCall)
}

func (fake *FakeRenderer) RenderArgsForCall(i int) render.Queue {
	fake.renderMutex.RLock()
	defer fake.renderMutex.RUnlock()
	return fake.renderArgsForCall[i].arg1
}

var _ render.Renderer = new(FakeRenderer)
