// This file was generated by counterfeiter
package shader_fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics/client"
	"github.com/momchil-atanasov/go-whiskey/graphics/shader"
)

type FakeShader struct {
	DataStub        func() shader.ShaderData
	dataMutex       sync.RWMutex
	dataArgsForCall []struct{}
	dataReturns struct {
		result1 shader.ShaderData
	}
	IdStub        func() client.ShaderId
	idMutex       sync.RWMutex
	idArgsForCall []struct{}
	idReturns struct {
		result1 client.ShaderId
	}
	CreatedStub        func() bool
	createdMutex       sync.RWMutex
	createdArgsForCall []struct{}
	createdReturns struct {
		result1 bool
	}
	CreateStub        func(client.ShaderClient) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 client.ShaderClient
	}
	createReturns struct {
		result1 error
	}
	DeleteStub        func(client.ShaderClient) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 client.ShaderClient
	}
	deleteReturns struct {
		result1 error
	}
}

func (fake *FakeShader) Data() shader.ShaderData {
	fake.dataMutex.Lock()
	fake.dataArgsForCall = append(fake.dataArgsForCall, struct{}{})
	fake.dataMutex.Unlock()
	if fake.DataStub != nil {
		return fake.DataStub()
	} else {
		return fake.dataReturns.result1
	}
}

func (fake *FakeShader) DataCallCount() int {
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	return len(fake.dataArgsForCall)
}

func (fake *FakeShader) DataReturns(result1 shader.ShaderData) {
	fake.DataStub = nil
	fake.dataReturns = struct {
		result1 shader.ShaderData
	}{result1}
}

func (fake *FakeShader) Id() client.ShaderId {
	fake.idMutex.Lock()
	fake.idArgsForCall = append(fake.idArgsForCall, struct{}{})
	fake.idMutex.Unlock()
	if fake.IdStub != nil {
		return fake.IdStub()
	} else {
		return fake.idReturns.result1
	}
}

func (fake *FakeShader) IdCallCount() int {
	fake.idMutex.RLock()
	defer fake.idMutex.RUnlock()
	return len(fake.idArgsForCall)
}

func (fake *FakeShader) IdReturns(result1 client.ShaderId) {
	fake.IdStub = nil
	fake.idReturns = struct {
		result1 client.ShaderId
	}{result1}
}

func (fake *FakeShader) Created() bool {
	fake.createdMutex.Lock()
	fake.createdArgsForCall = append(fake.createdArgsForCall, struct{}{})
	fake.createdMutex.Unlock()
	if fake.CreatedStub != nil {
		return fake.CreatedStub()
	} else {
		return fake.createdReturns.result1
	}
}

func (fake *FakeShader) CreatedCallCount() int {
	fake.createdMutex.RLock()
	defer fake.createdMutex.RUnlock()
	return len(fake.createdArgsForCall)
}

func (fake *FakeShader) CreatedReturns(result1 bool) {
	fake.CreatedStub = nil
	fake.createdReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeShader) Create(arg1 client.ShaderClient) error {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 client.ShaderClient
	}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	} else {
		return fake.createReturns.result1
	}
}

func (fake *FakeShader) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeShader) CreateArgsForCall(i int) client.ShaderClient {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *FakeShader) CreateReturns(result1 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeShader) Delete(arg1 client.ShaderClient) error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 client.ShaderClient
	}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeShader) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeShader) DeleteArgsForCall(i int) client.ShaderClient {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].arg1
}

func (fake *FakeShader) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

var _ shader.Shader = new(FakeShader)
