// This file was generated by counterfeiter
package shader_fakes

import (
	"sync"

	"github.com/momchil-atanasov/go-whiskey/graphics/client"
	"github.com/momchil-atanasov/go-whiskey/graphics/shader"
)

type FakeRemoteProgram struct {
	IdStub        func() client.ProgramId
	idMutex       sync.RWMutex
	idArgsForCall []struct{}
	idReturns struct {
		result1 client.ProgramId
	}
	CreatedStub        func() bool
	createdMutex       sync.RWMutex
	createdArgsForCall []struct{}
	createdReturns struct {
		result1 bool
	}
	CreateStub        func() error
	createMutex       sync.RWMutex
	createArgsForCall []struct{}
	createReturns struct {
		result1 error
	}
	DeleteStub        func() error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct{}
	deleteReturns struct {
		result1 error
	}
	UseStub        func() error
	useMutex       sync.RWMutex
	useArgsForCall []struct{}
	useReturns struct {
		result1 error
	}
}

func (fake *FakeRemoteProgram) Id() client.ProgramId {
	fake.idMutex.Lock()
	fake.idArgsForCall = append(fake.idArgsForCall, struct{}{})
	fake.idMutex.Unlock()
	if fake.IdStub != nil {
		return fake.IdStub()
	} else {
		return fake.idReturns.result1
	}
}

func (fake *FakeRemoteProgram) IdCallCount() int {
	fake.idMutex.RLock()
	defer fake.idMutex.RUnlock()
	return len(fake.idArgsForCall)
}

func (fake *FakeRemoteProgram) IdReturns(result1 client.ProgramId) {
	fake.IdStub = nil
	fake.idReturns = struct {
		result1 client.ProgramId
	}{result1}
}

func (fake *FakeRemoteProgram) Created() bool {
	fake.createdMutex.Lock()
	fake.createdArgsForCall = append(fake.createdArgsForCall, struct{}{})
	fake.createdMutex.Unlock()
	if fake.CreatedStub != nil {
		return fake.CreatedStub()
	} else {
		return fake.createdReturns.result1
	}
}

func (fake *FakeRemoteProgram) CreatedCallCount() int {
	fake.createdMutex.RLock()
	defer fake.createdMutex.RUnlock()
	return len(fake.createdArgsForCall)
}

func (fake *FakeRemoteProgram) CreatedReturns(result1 bool) {
	fake.CreatedStub = nil
	fake.createdReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeRemoteProgram) Create() error {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct{}{})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub()
	} else {
		return fake.createReturns.result1
	}
}

func (fake *FakeRemoteProgram) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeRemoteProgram) CreateReturns(result1 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRemoteProgram) Delete() error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct{}{})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub()
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeRemoteProgram) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeRemoteProgram) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRemoteProgram) Use() error {
	fake.useMutex.Lock()
	fake.useArgsForCall = append(fake.useArgsForCall, struct{}{})
	fake.useMutex.Unlock()
	if fake.UseStub != nil {
		return fake.UseStub()
	} else {
		return fake.useReturns.result1
	}
}

func (fake *FakeRemoteProgram) UseCallCount() int {
	fake.useMutex.RLock()
	defer fake.useMutex.RUnlock()
	return len(fake.useArgsForCall)
}

func (fake *FakeRemoteProgram) UseReturns(result1 error) {
	fake.UseStub = nil
	fake.useReturns = struct {
		result1 error
	}{result1}
}

var _ shader.RemoteProgram = new(FakeRemoteProgram)
